version: '3.4'

services:
  # webapi:
  #   build: 
  #     context: .
  #     dockerfile: /src/FoodTruck.WebApi/Dockerfile
  #   depends_on: 
  #     - database
  tests:
    build: 
      context: .
      dockerfile: ./tests/FoodTruck.DatabaseTests/Dockerfile
    depends_on: 
      - database
    environment:
      WAIT_HOSTS: database:1433
    # volumes:
        # - /opt/vsts/work/_temp:/var/temp
        #this is for the pipeline

  database:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
        SA_PASSWORD: "P@ssW0rd!"
        ACCEPT_EULA: "Y"